version: '1'
services:
  app:
    build:
      context: .
    ports:
        - 8082:8082
    depends_on:
        - database
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: Qazwsxedc123
  database:
    image: postgres
    container_name: "diploma_database"
    ports:
      - 5433:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qazwsxedc123
      POSTRGRES_DATABASE: postgres